# Generated by Django 3.0.5 on 2020-05-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_auto_20200503_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
