# Generated by Django 3.0.5 on 2020-05-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_auto_20200505_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reting',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='RetingStar',
            new_name='RatingStar',
        ),
    ]
