# Generated by Django 3.0.5 on 2020-05-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_auto_20200512_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актёр и режиссёр', 'verbose_name_plural': 'Актёры и режиссёры'},
        ),
    ]
